services:
  core:
    container_name: global-devcontainer-core
    userns_mode: keep-id
    tmpfs:
      - /home/global/workspace/tmp:uid=1000,gid=1000
      - /home/global/workspace/log:uid=1000,gid=1000
    environment:
      - DEVCONTAINER=1
      - RUBY_DEBUG_OPEN=false
  primary:
    container_name: global-devcontainer-primary
    ports: []
  replica:
    container_name: global-devcontainer-replica
    ports: []
  valkey:
    container_name: global-devcontainer-valkey
    ports: []
  master:
    container_name: global-devcontainer-seaweedfs-master
    ports: []
  volume:
    container_name: global-devcontainer-seaweedfs-volume
    ports: []
  filer:
    container_name: global-devcontainer-seaweedfs-filer
    ports: []
  s3:
    container_name: global-devcontainer-seaweedfs-s3
    ports: []
  loki:
    container_name: global-devcontainer-loki
    ports: []
  tempo:
    container_name: global-devcontainer-tempo
    ports: []
  grafana:
    container_name: global-devcontainer-grafana
    ports: []
